"""PullSense Server — Agents: Base agent abstractions and output schemas."""

from __future__ import annotations

import os
from abc import ABC, abstractmethod
from typing import Any

from pydantic import BaseModel, Field

from server.config import Settings, get_settings
from server.domains.agents.runner import AgentExecutionResult, run_gemini_agent
from server.domains.github.schemas import PRDiffContext
from server.infrastructure import get_logger

logger = get_logger(__name__)

PROMPTS_DIR = os.path.join(os.path.dirname(__file__), "prompts")


# ── Agent Output Schemas ──────────────────────────────────────────────


class TriageOutput(BaseModel):
    """Output generated by the Triage Agent."""

    classification: str = "medium"  # small | medium | large | critical
    summary: str = ""
    risk_score: int = 5
    recommended_agents: list[str] = Field(default_factory=lambda: ["security", "style"])


class RawFinding(BaseModel):
    """An individual finding identified by a review agent."""

    severity: str = "suggestion"  # critical | warning | suggestion | info
    category: str = "general"
    file_path: str | None = None
    start_line: int | None = None
    end_line: int | None = None
    title: str
    description: str
    suggestion: str | None = None
    code_snippet: str | None = None


class AgentFindingList(BaseModel):
    """Collection of findings from a specialized review agent."""

    findings: list[RawFinding] = Field(default_factory=list)


class AggregatorFinding(RawFinding):
    """A prioritized, de-duplicated finding produced by the Aggregator Agent."""

    agent_name: str = "aggregator"


class AggregatorOutput(BaseModel):
    """Final synthesized review generated by the Aggregator Agent."""

    summary: str = ""
    findings: list[AggregatorFinding] = Field(default_factory=list)


# ── Base Agent Class ──────────────────────────────────────────────────


class BaseAgent[T: BaseModel](ABC):
    """Abstract base class for all PullSense AI review agents."""

    name: str = "base"
    system_prompt_filename: str = ""
    temperature: float = 0.2
    max_output_tokens: int = 4096

    def __init__(self, model_name: str | None = None, settings: Settings | None = None) -> None:
        self.settings = settings or get_settings()
        self.model_name = model_name or self.settings.gemini_flash_model
        self._system_prompt: str | None = None

    def get_system_prompt(self) -> str:
        """Load the system prompt markdown file from the prompts directory."""
        if self._system_prompt is None:
            prompt_path = os.path.join(PROMPTS_DIR, self.system_prompt_filename)
            with open(prompt_path, encoding="utf-8") as f:
                self._system_prompt = f.read()
        return self._system_prompt

    @abstractmethod
    def build_user_prompt(self, context: PRDiffContext, **kwargs: Any) -> str:
        """Build the user prompt containing relevant PR diff and file context."""
        pass

    @abstractmethod
    def parse_output(self, parsed_json: dict[str, Any]) -> T:
        """Parse raw JSON output from the LLM into a validated Pydantic model."""
        pass

    async def run(self, context: PRDiffContext, **kwargs: Any) -> tuple[T, AgentExecutionResult]:
        """Execute the agent against the PR context and return typed output + metrics."""
        system_instruction = self.get_system_prompt()
        user_prompt = self.build_user_prompt(context, **kwargs)

        logger.info(
            "agent_starting",
            agent=self.name,
            model=self.model_name,
            pr_number=context.pr_number,
        )

        exec_result = await run_gemini_agent(
            model_name=self.model_name,
            system_instruction=system_instruction,
            user_prompt=user_prompt,
            temperature=self.temperature,
            max_output_tokens=self.max_output_tokens,
            settings=self.settings,
        )

        parsed_output = self.parse_output(exec_result.parsed_json)
        return parsed_output, exec_result
